ALTER TABLE users
ADD COLUMN created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_date DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN updated_by VARCHAR(255) DEFAULT NULL,
ADD COLUMN deleted_at DATETIME DEFAULT NULL;

ALTER TABLE authorities
ADD COLUMN created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN updated_date DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN updated_by VARCHAR(255) DEFAULT NULL,
ADD COLUMN deleted_at DATETIME DEFAULT NULL;

